package android.support.constraint;

public final class R {
    private R() {
    }

    public static final class attr {
        public static final int barrierAllowsGoneWidgets = 2130903100;
        public static final int barrierDirection = 2130903101;
        public static final int chainUseRtl = 2130903144;
        public static final int constraintSet = 2130903208;
        public static final int constraint_referenced_ids = 2130903209;
        public static final int content = 2130903210;
        public static final int emptyVisibility = 2130903251;
        public static final int layout_constrainedHeight = 2130903346;
        public static final int layout_constrainedWidth = 2130903347;
        public static final int layout_constraintBaseline_creator = 2130903348;
        public static final int layout_constraintBaseline_toBaselineOf = 2130903349;
        public static final int layout_constraintBottom_creator = 2130903350;
        public static final int layout_constraintBottom_toBottomOf = 2130903351;
        public static final int layout_constraintBottom_toTopOf = 2130903352;
        public static final int layout_constraintCircle = 2130903353;
        public static final int layout_constraintCircleAngle = 2130903354;
        public static final int layout_constraintCircleRadius = 2130903355;
        public static final int layout_constraintDimensionRatio = 2130903356;
        public static final int layout_constraintEnd_toEndOf = 2130903357;
        public static final int layout_constraintEnd_toStartOf = 2130903358;
        public static final int layout_constraintGuide_begin = 2130903359;
        public static final int layout_constraintGuide_end = 2130903360;
        public static final int layout_constraintGuide_percent = 2130903361;
        public static final int layout_constraintHeight_default = 2130903362;
        public static final int layout_constraintHeight_max = 2130903363;
        public static final int layout_constraintHeight_min = 2130903364;
        public static final int layout_constraintHeight_percent = 2130903365;
        public static final int layout_constraintHorizontal_bias = 2130903366;
        public static final int layout_constraintHorizontal_chainStyle = 2130903367;
        public static final int layout_constraintHorizontal_weight = 2130903368;
        public static final int layout_constraintLeft_creator = 2130903369;
        public static final int layout_constraintLeft_toLeftOf = 2130903370;
        public static final int layout_constraintLeft_toRightOf = 2130903371;
        public static final int layout_constraintRight_creator = 2130903372;
        public static final int layout_constraintRight_toLeftOf = 2130903373;
        public static final int layout_constraintRight_toRightOf = 2130903374;
        public static final int layout_constraintStart_toEndOf = 2130903375;
        public static final int layout_constraintStart_toStartOf = 2130903376;
        public static final int layout_constraintTop_creator = 2130903377;
        public static final int layout_constraintTop_toBottomOf = 2130903378;
        public static final int layout_constraintTop_toTopOf = 2130903379;
        public static final int layout_constraintVertical_bias = 2130903380;
        public static final int layout_constraintVertical_chainStyle = 2130903381;
        public static final int layout_constraintVertical_weight = 2130903382;
        public static final int layout_constraintWidth_default = 2130903383;
        public static final int layout_constraintWidth_max = 2130903384;
        public static final int layout_constraintWidth_min = 2130903385;
        public static final int layout_constraintWidth_percent = 2130903386;
        public static final int layout_editor_absoluteX = 2130903388;
        public static final int layout_editor_absoluteY = 2130903389;
        public static final int layout_goneMarginBottom = 2130903390;
        public static final int layout_goneMarginEnd = 2130903391;
        public static final int layout_goneMarginLeft = 2130903392;
        public static final int layout_goneMarginRight = 2130903393;
        public static final int layout_goneMarginStart = 2130903394;
        public static final int layout_goneMarginTop = 2130903395;
        public static final int layout_optimizationLevel = 2130903398;

        private attr() {
        }
    }

    public static final class id {
        public static final int bottom = 2131296296;
        public static final int end = 2131296349;
        public static final int gone = 2131296386;
        public static final int invisible = 2131296399;
        public static final int left = 2131296406;
        public static final int packed = 2131296431;
        public static final int parent = 2131296434;
        public static final int percent = 2131296437;
        public static final int right = 2131296447;
        public static final int spread = 2131296484;
        public static final int spread_inside = 2131296485;
        public static final int start = 2131296490;
        public static final int top = 2131296523;
        public static final int wrap = 2131296540;

        private id() {
        }
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout = {16842948, 16843039, 16843040, 16843071, 16843072, com.liber8tech.tago.R.attr.barrierAllowsGoneWidgets, com.liber8tech.tago.R.attr.barrierDirection, com.liber8tech.tago.R.attr.chainUseRtl, com.liber8tech.tago.R.attr.constraintSet, com.liber8tech.tago.R.attr.constraint_referenced_ids, com.liber8tech.tago.R.attr.layout_constrainedHeight, com.liber8tech.tago.R.attr.layout_constrainedWidth, com.liber8tech.tago.R.attr.layout_constraintBaseline_creator, com.liber8tech.tago.R.attr.layout_constraintBaseline_toBaselineOf, com.liber8tech.tago.R.attr.layout_constraintBottom_creator, com.liber8tech.tago.R.attr.layout_constraintBottom_toBottomOf, com.liber8tech.tago.R.attr.layout_constraintBottom_toTopOf, com.liber8tech.tago.R.attr.layout_constraintCircle, com.liber8tech.tago.R.attr.layout_constraintCircleAngle, com.liber8tech.tago.R.attr.layout_constraintCircleRadius, com.liber8tech.tago.R.attr.layout_constraintDimensionRatio, com.liber8tech.tago.R.attr.layout_constraintEnd_toEndOf, com.liber8tech.tago.R.attr.layout_constraintEnd_toStartOf, com.liber8tech.tago.R.attr.layout_constraintGuide_begin, com.liber8tech.tago.R.attr.layout_constraintGuide_end, com.liber8tech.tago.R.attr.layout_constraintGuide_percent, com.liber8tech.tago.R.attr.layout_constraintHeight_default, com.liber8tech.tago.R.attr.layout_constraintHeight_max, com.liber8tech.tago.R.attr.layout_constraintHeight_min, com.liber8tech.tago.R.attr.layout_constraintHeight_percent, com.liber8tech.tago.R.attr.layout_constraintHorizontal_bias, com.liber8tech.tago.R.attr.layout_constraintHorizontal_chainStyle, com.liber8tech.tago.R.attr.layout_constraintHorizontal_weight, com.liber8tech.tago.R.attr.layout_constraintLeft_creator, com.liber8tech.tago.R.attr.layout_constraintLeft_toLeftOf, com.liber8tech.tago.R.attr.layout_constraintLeft_toRightOf, com.liber8tech.tago.R.attr.layout_constraintRight_creator, com.liber8tech.tago.R.attr.layout_constraintRight_toLeftOf, com.liber8tech.tago.R.attr.layout_constraintRight_toRightOf, com.liber8tech.tago.R.attr.layout_constraintStart_toEndOf, com.liber8tech.tago.R.attr.layout_constraintStart_toStartOf, com.liber8tech.tago.R.attr.layout_constraintTop_creator, com.liber8tech.tago.R.attr.layout_constraintTop_toBottomOf, com.liber8tech.tago.R.attr.layout_constraintTop_toTopOf, com.liber8tech.tago.R.attr.layout_constraintVertical_bias, com.liber8tech.tago.R.attr.layout_constraintVertical_chainStyle, com.liber8tech.tago.R.attr.layout_constraintVertical_weight, com.liber8tech.tago.R.attr.layout_constraintWidth_default, com.liber8tech.tago.R.attr.layout_constraintWidth_max, com.liber8tech.tago.R.attr.layout_constraintWidth_min, com.liber8tech.tago.R.attr.layout_constraintWidth_percent, com.liber8tech.tago.R.attr.layout_editor_absoluteX, com.liber8tech.tago.R.attr.layout_editor_absoluteY, com.liber8tech.tago.R.attr.layout_goneMarginBottom, com.liber8tech.tago.R.attr.layout_goneMarginEnd, com.liber8tech.tago.R.attr.layout_goneMarginLeft, com.liber8tech.tago.R.attr.layout_goneMarginRight, com.liber8tech.tago.R.attr.layout_goneMarginStart, com.liber8tech.tago.R.attr.layout_goneMarginTop, com.liber8tech.tago.R.attr.layout_optimizationLevel};
        public static final int ConstraintLayout_Layout_android_maxHeight = 2;
        public static final int ConstraintLayout_Layout_android_maxWidth = 1;
        public static final int ConstraintLayout_Layout_android_minHeight = 4;
        public static final int ConstraintLayout_Layout_android_minWidth = 3;
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
        public static final int ConstraintLayout_Layout_barrierDirection = 6;
        public static final int ConstraintLayout_Layout_chainUseRtl = 7;
        public static final int ConstraintLayout_Layout_constraintSet = 8;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids = 9;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight = 10;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth = 11;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
        public static final int ConstraintLayout_Layout_layout_constraintCircle = 17;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 56;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 57;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 58;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel = 59;
        public static final int[] ConstraintLayout_placeholder = {com.liber8tech.tago.R.attr.content, com.liber8tech.tago.R.attr.emptyVisibility};
        public static final int ConstraintLayout_placeholder_content = 0;
        public static final int ConstraintLayout_placeholder_emptyVisibility = 1;
        public static final int[] ConstraintSet = {16842948, 16842960, 16842972, 16842996, 16842997, 16842999, 16843000, 16843001, 16843002, 16843039, 16843040, 16843071, 16843072, 16843551, 16843552, 16843553, 16843554, 16843555, 16843556, 16843557, 16843558, 16843559, 16843560, 16843701, 16843702, 16843770, 16843840, com.liber8tech.tago.R.attr.barrierAllowsGoneWidgets, com.liber8tech.tago.R.attr.barrierDirection, com.liber8tech.tago.R.attr.chainUseRtl, com.liber8tech.tago.R.attr.constraint_referenced_ids, com.liber8tech.tago.R.attr.layout_constrainedHeight, com.liber8tech.tago.R.attr.layout_constrainedWidth, com.liber8tech.tago.R.attr.layout_constraintBaseline_creator, com.liber8tech.tago.R.attr.layout_constraintBaseline_toBaselineOf, com.liber8tech.tago.R.attr.layout_constraintBottom_creator, com.liber8tech.tago.R.attr.layout_constraintBottom_toBottomOf, com.liber8tech.tago.R.attr.layout_constraintBottom_toTopOf, com.liber8tech.tago.R.attr.layout_constraintCircle, com.liber8tech.tago.R.attr.layout_constraintCircleAngle, com.liber8tech.tago.R.attr.layout_constraintCircleRadius, com.liber8tech.tago.R.attr.layout_constraintDimensionRatio, com.liber8tech.tago.R.attr.layout_constraintEnd_toEndOf, com.liber8tech.tago.R.attr.layout_constraintEnd_toStartOf, com.liber8tech.tago.R.attr.layout_constraintGuide_begin, com.liber8tech.tago.R.attr.layout_constraintGuide_end, com.liber8tech.tago.R.attr.layout_constraintGuide_percent, com.liber8tech.tago.R.attr.layout_constraintHeight_default, com.liber8tech.tago.R.attr.layout_constraintHeight_max, com.liber8tech.tago.R.attr.layout_constraintHeight_min, com.liber8tech.tago.R.attr.layout_constraintHeight_percent, com.liber8tech.tago.R.attr.layout_constraintHorizontal_bias, com.liber8tech.tago.R.attr.layout_constraintHorizontal_chainStyle, com.liber8tech.tago.R.attr.layout_constraintHorizontal_weight, com.liber8tech.tago.R.attr.layout_constraintLeft_creator, com.liber8tech.tago.R.attr.layout_constraintLeft_toLeftOf, com.liber8tech.tago.R.attr.layout_constraintLeft_toRightOf, com.liber8tech.tago.R.attr.layout_constraintRight_creator, com.liber8tech.tago.R.attr.layout_constraintRight_toLeftOf, com.liber8tech.tago.R.attr.layout_constraintRight_toRightOf, com.liber8tech.tago.R.attr.layout_constraintStart_toEndOf, com.liber8tech.tago.R.attr.layout_constraintStart_toStartOf, com.liber8tech.tago.R.attr.layout_constraintTop_creator, com.liber8tech.tago.R.attr.layout_constraintTop_toBottomOf, com.liber8tech.tago.R.attr.layout_constraintTop_toTopOf, com.liber8tech.tago.R.attr.layout_constraintVertical_bias, com.liber8tech.tago.R.attr.layout_constraintVertical_chainStyle, com.liber8tech.tago.R.attr.layout_constraintVertical_weight, com.liber8tech.tago.R.attr.layout_constraintWidth_default, com.liber8tech.tago.R.attr.layout_constraintWidth_max, com.liber8tech.tago.R.attr.layout_constraintWidth_min, com.liber8tech.tago.R.attr.layout_constraintWidth_percent, com.liber8tech.tago.R.attr.layout_editor_absoluteX, com.liber8tech.tago.R.attr.layout_editor_absoluteY, com.liber8tech.tago.R.attr.layout_goneMarginBottom, com.liber8tech.tago.R.attr.layout_goneMarginEnd, com.liber8tech.tago.R.attr.layout_goneMarginLeft, com.liber8tech.tago.R.attr.layout_goneMarginRight, com.liber8tech.tago.R.attr.layout_goneMarginStart, com.liber8tech.tago.R.attr.layout_goneMarginTop};
        public static final int ConstraintSet_android_alpha = 13;
        public static final int ConstraintSet_android_elevation = 26;
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 24;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 23;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_maxHeight = 10;
        public static final int ConstraintSet_android_maxWidth = 9;
        public static final int ConstraintSet_android_minHeight = 12;
        public static final int ConstraintSet_android_minWidth = 11;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_rotation = 20;
        public static final int ConstraintSet_android_rotationX = 21;
        public static final int ConstraintSet_android_rotationY = 22;
        public static final int ConstraintSet_android_scaleX = 18;
        public static final int ConstraintSet_android_scaleY = 19;
        public static final int ConstraintSet_android_transformPivotX = 14;
        public static final int ConstraintSet_android_transformPivotY = 15;
        public static final int ConstraintSet_android_translationX = 16;
        public static final int ConstraintSet_android_translationY = 17;
        public static final int ConstraintSet_android_translationZ = 25;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_barrierAllowsGoneWidgets = 27;
        public static final int ConstraintSet_barrierDirection = 28;
        public static final int ConstraintSet_chainUseRtl = 29;
        public static final int ConstraintSet_constraint_referenced_ids = 30;
        public static final int ConstraintSet_layout_constrainedHeight = 31;
        public static final int ConstraintSet_layout_constrainedWidth = 32;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 33;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 34;
        public static final int ConstraintSet_layout_constraintBottom_creator = 35;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 36;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 37;
        public static final int ConstraintSet_layout_constraintCircle = 38;
        public static final int ConstraintSet_layout_constraintCircleAngle = 39;
        public static final int ConstraintSet_layout_constraintCircleRadius = 40;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 41;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 42;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 43;
        public static final int ConstraintSet_layout_constraintGuide_begin = 44;
        public static final int ConstraintSet_layout_constraintGuide_end = 45;
        public static final int ConstraintSet_layout_constraintGuide_percent = 46;
        public static final int ConstraintSet_layout_constraintHeight_default = 47;
        public static final int ConstraintSet_layout_constraintHeight_max = 48;
        public static final int ConstraintSet_layout_constraintHeight_min = 49;
        public static final int ConstraintSet_layout_constraintHeight_percent = 50;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 51;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle = 52;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 53;
        public static final int ConstraintSet_layout_constraintLeft_creator = 54;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 55;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 56;
        public static final int ConstraintSet_layout_constraintRight_creator = 57;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 58;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 59;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 60;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 61;
        public static final int ConstraintSet_layout_constraintTop_creator = 62;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 63;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 64;
        public static final int ConstraintSet_layout_constraintVertical_bias = 65;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle = 66;
        public static final int ConstraintSet_layout_constraintVertical_weight = 67;
        public static final int ConstraintSet_layout_constraintWidth_default = 68;
        public static final int ConstraintSet_layout_constraintWidth_max = 69;
        public static final int ConstraintSet_layout_constraintWidth_min = 70;
        public static final int ConstraintSet_layout_constraintWidth_percent = 71;
        public static final int ConstraintSet_layout_editor_absoluteX = 72;
        public static final int ConstraintSet_layout_editor_absoluteY = 73;
        public static final int ConstraintSet_layout_goneMarginBottom = 74;
        public static final int ConstraintSet_layout_goneMarginEnd = 75;
        public static final int ConstraintSet_layout_goneMarginLeft = 76;
        public static final int ConstraintSet_layout_goneMarginRight = 77;
        public static final int ConstraintSet_layout_goneMarginStart = 78;
        public static final int ConstraintSet_layout_goneMarginTop = 79;
        public static final int[] LinearConstraintLayout = {16842948};
        public static final int LinearConstraintLayout_android_orientation = 0;

        private styleable() {
        }
    }
}
